version: '3.8'
services:
  app:
    image: product-cart-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    volumes:
      - ./data:/db:rw
