name: Run Integration Tests
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: zulu
      - name: Build Jar
        run: ./gradlew clean bootJar
      - name: Build Docker
        run: docker-compose build
      - name: Run Product Cart Service
        run: docker-compose up
      - name: Wait for 10 seconds
        uses: actions/starter-workflows/.github/actions/sleep@main
        with:
          time: 10s
      - name: Run Integration Tests
        run: ./gradlew integrationTest
      - name: Stop Service and Remove
        run: docker-compose down
